name: ROS2 CI Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      # 1) Check out only the "loadcell" package into the current folder
      - name: Checkout only fbg directory
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            loadcell/
          fetch-depth: 1

      # 2) Install ROS 2 Humble dependencies
      - name: Setup ROS2
        shell: bash
        run: |
          sudo apt update
          sudo apt install -y curl gnupg lsb-release
          sudo curl -sSL https://raw.githubusercontent.com/ros/rosdistro/master/ros.key | sudo apt-key add -
          echo "deb http://packages.ros.org/ros2/ubuntu $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/ros2.list
          sudo apt update
          sudo apt install -y ros-humble-ros-base python3-colcon-common-extensions python3-rosdep python3-vcstool build-essential
          sudo rosdep init || true
          rosdep update

      # 3) Create the ROS2 workspace and move "loadcell" into src
      - name: Prepare workspace
        shell: bash
        run: |
          mkdir -p ros2_ws/src
          mv laodcell ros2_ws/src

      # 4) Build and test package in the workspace
      - name: Build and Test
        shell: bash
        run: |
          source /opt/ros/humble/setup.bash
          cd ros2_ws
          # Install any missing dependencies
          rosdep install --from-paths src --ignore-src -r -y
          # Build all packages (loadcell)
          colcon build --symlink-install
          # Run tests, fail the job if tests fail
          colcon test --return-code-on-test-failure --event-handlers console_cohesion+

      # 5) upload results
      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: ros2_ws/build/**/test_results/**/*.xml
